<?php
/**
 * includes/billing_pdf.php
 *
 * Hub for the FIA Billing Report PDF (formerly referred to internally as the
 * "CNA report" — CNA is just one client; this is used for all of them).
 * Generated by the office at billing time. Fetches data and delegates to the
 * template-based renderer.
 *
 * Renderer: pdf/generate_billing_template.php
 *   Overlays data onto the CorelDraw-sourced shell PDF (templates/cmi-template-shell.pdf)
 *   using FPDI + TCPDF, then appends photo/video appendix pages.
 *
 * Storage:
 *   Unlike the in-shop worksheet (generated on demand, never persisted),
 *   Billing Reports must be retained for at least one year. They are written
 *   to disk OUTSIDE the web root, flat (no per-FIA subfolders — the fia_number
 *   is already in the filename, so a folder-per-report would just hold one
 *   file each), at:
 *       {PRIVATE_PATH}/billing_reports/FIA_Report_{fia_number}.pdf
 *   Re-generating a report overwrites the existing file (fixed filename —
 *   no versioning). No DB tracking table; the filesystem is authoritative.
 *
 * Public API:
 *   billing_pdf_bytes(int $fia_number, mysqli $db): string|false
 *       Returns raw PDF bytes, or false if the inspection is not found.
 *
 *   billing_pdf_save(int $fia_number, mysqli $db): string|false
 *       Generates, writes (overwriting) to the archive path, and returns the
 *       absolute file path written. Returns false on failure.
 *
 *   billing_pdf_stream(int $fia_number, mysqli $db, string $filename = ''): void
 *       Streams the PDF directly to the browser as an inline download.
 *       Calls exit on completion.
 */

if (!defined('WEB_ROOT')) {
    require_once 'C:\inetpub\fia_private\config.php';
}
require_once WEB_ROOT . '/vendor/autoload.php';

// ---------------------------------------------------------------------------
// Where archived Billing Report PDFs live (outside the web root)
// ---------------------------------------------------------------------------
if (!defined('BILLING_REPORT_PATH')) {
    define('BILLING_REPORT_PATH', PRIVATE_PATH . '/billing_reports');
}

/**
 * Absolute path to the (over-writable) archive copy of a Billing Report.
 */
function billing_pdf_path(int $fia): string
{
    return BILLING_REPORT_PATH . '/FIA_Report_' . $fia . '.pdf';
}

// ---------------------------------------------------------------------------
// Internal: fetch all data needed for the Billing Report
// ---------------------------------------------------------------------------
function _billing_fetch(int $fia, mysqli $db): array|false
{
    $stmt = $db->prepare("
        SELECT
            i.fia_number,
            i.claim_number,
            i.contract_number,
            i.insured,
            i.year, i.make, i.model, i.color,
            i.complete_vin,
            i.vin,
            i.current_mileage,
            i.mileage,
            i.tag, i.tag_state,
            i.repair_shop,
            i.address           AS shop_address,
            i.city              AS shop_city,
            i.state_code        AS shop_state_code,
            i.zip               AS shop_zip,
            i.phone_number      AS shop_phone_number,
            i.contact           AS shop_contact,
            i.called_in_by,
            i.created_at,
            i.created_date,
            i.created_time,
            i.date_of_inspection,
            i.ro_no,
            i.ro_date,

            -- Vehicle / mechanical
            i.trailer_hitch,
            i.towed_driven,
            i.engine_size,
            i.transmission_type,
            i.drive_train,
            i.overall_condition,

            -- Fluids (level / condition pairs)
            i.engine_oil_level,      i.engine_oil_cond,
            i.coolant_level,         i.coolant_cond,
            i.brake_fluid_level,     i.brake_fluid_cond,
            i.power_steering_level,  i.power_steering_cond,
            i.trans_fluid_level,     i.trans_fluid_cond,

            -- Narrative / report fields
            i.customer_complaint,
            i.inspectors_report,
            i.cause_of_failure,
            i.recommended_repairs,
            i.shop_comments,
            i.shop_of_failure,
            i.modifications,
            i.commercial_use,
            i.impact_damage,
            i.service_history_avail,
            i.amount_of_teardown,

            -- Billing / fees
            i.base_fee,
            i.fuel_surcharge,
            i.special_charges,
            i.inspection_fee,
            i.labor_rate,
            i.notes_on_email,
            i.did_shop_sign_report,
            i.shop_rep_name,

            -- Related
            w.company_name,
            ins.full_name           AS inspector_full_name
        FROM inspections i
        LEFT JOIN warranty_co  w   ON w.warranty_co_id  = i.warranty_co_id
        LEFT JOIN inspectors   ins ON ins.inspector_id  = i.inspector_id
        WHERE i.fia_number = ?
        LIMIT 1
    ");
    if (!$stmt) return false;
    $stmt->bind_param('i', $fia);
    if (!$stmt->execute()) { $stmt->close(); return false; }
    $row = $stmt->get_result()->fetch_assoc();
    $stmt->close();
    if (!$row) return false;

    // Format date/time from created_at timestamp (fall back to stored strings)
    if (empty($row['created_date']) && !empty($row['created_at'])) {
        $row['created_date'] = date('n/j/Y',   strtotime($row['created_at']));
    }
    if (empty($row['created_time']) && !empty($row['created_at'])) {
        $row['created_time'] = date('g:i:s A', strtotime($row['created_at']));
    }

    // FIA Total Fee — sum of the fee components if not separately stored
    $row['fia_total_fee'] = number_format(
        (float)($row['base_fee'] ?? 0)
        + (float)($row['fuel_surcharge'] ?? 0)
        + (float)($row['special_charges'] ?? 0),
        2
    );

    // -------------------------------------------------------------------
    // Photos / videos for the appendix (non-archived, in upload order)
    // -------------------------------------------------------------------
    $pic_stmt = $db->prepare(
        "SELECT picture_id, image_path, caption, uploaded_at
           FROM pictures
          WHERE fia_number = ? AND is_archived = FALSE
          ORDER BY uploaded_at, picture_id"
    );
    $pic_stmt->bind_param('i', $fia);
    $pic_stmt->execute();
    $row['media'] = $pic_stmt->get_result()->fetch_all(MYSQLI_ASSOC);
    $pic_stmt->close();

    return $row;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate Billing Report PDF bytes. Returns false if inspection not found.
 * $opts keys: 'no_photos' (bool) — skip the photo appendix.
 */
function billing_pdf_bytes(int $fia, mysqli $db, array $opts = []): string|false
{
    $data = _billing_fetch($fia, $db);
    if (!$data) return false;
    require_once __DIR__ . '/../pdf/generate_billing_template.php';
    return generateBillingReport($data, $opts);
}

/**
 * Generate and write the Billing Report to its archive location, overwriting
 * any existing copy. Returns the absolute path written, or false on failure.
 * Always includes photos — $opts suppression is for preview only.
 */
function billing_pdf_save(int $fia, mysqli $db): string|false
{
    $bytes = billing_pdf_bytes($fia, $db);   // no $opts — photos always included
    if ($bytes === false) return false;

    $path = billing_pdf_path($fia);
    $dir  = dirname($path);
    if (!is_dir($dir) && !mkdir($dir, 0755, true)) {
        error_log("billing_pdf_save: failed to create directory {$dir}");
        return false;
    }
    if (file_put_contents($path, $bytes) === false) {
        error_log("billing_pdf_save: failed to write {$path}");
        return false;
    }
    return $path;
}

/**
 * Stream the Billing Report PDF to the browser.
 * $opts keys: 'no_photos' (bool) — skip the photo appendix (preview only).
 */
function billing_pdf_stream(int $fia, mysqli $db, string $filename = '', array $opts = []): void
{
    $bytes = billing_pdf_bytes($fia, $db, $opts);
    if ($bytes === false) {
        http_response_code(404);
        echo 'Inspection not found.';
        exit;
    }
    if (!$filename) {
        $filename = 'FIA_Report_' . $fia . '.pdf';
    }
    header('Content-Type: application/pdf');
    header('Content-Disposition: inline; filename="' . $filename . '"');
    header('Content-Length: ' . strlen($bytes));
    header('Cache-Control: private, max-age=0, must-revalidate');
    echo $bytes;
    exit;
}
